### ISSUE TITLE
Odd values from Chrome on Windows

### ISSUE THREAD

**Issue by enguerranws** [monospaced/hamster.js#5] opened 2015-09-01 14:17 UTC
Hi,

I'm having a trouble when I try to get normalized values, especially for Chrome on Windows 7 : 
• for mouse wheel up and down, on Chrome Mac, on your demo website, I get values between : 400, -400
• on Firefox (both Windows and Mac), inertia makes values sometimes go crazy : 5000, -5000 but I can handle it
• on Chrome Windows, it's really weird, with the same test as above, I get : 4, -4 max.

What can i do ?

**Comment by monospaced** [comment] 2015-09-30 21:30
I think this is a duplicate of #1 

See my comment here:

https://github.com/monospaced/hamster.js/issues/1#issuecomment-52799009

The library needs updating, but unfortunately I am struggling to find the time :(

It could still happen!

**Closed by monospaced** 2015-09-30 21:30 UTC

**Comment by enguerranws** [comment] 2015-11-08 11:21
Well, actually, it's mostly hardware related issues : my tests on Mac were done with a Apple Magic Mouse (touch to scroll), when my test on Windows were done with a "classic" mouse (middle roller).

On a classic mouse : events are sent only on roller scale.
On mouse with touch scroll : events are sent whenever the finger moves on the surface, so it makes much more events to handle.

I made a dirty fix to prevent this (based on setInterval(), so really dirty) to "normalize" values on this two type of devices.
